### ISSUE TITLE
error with findVideoUrl: Cannot read properties of undefined (reading 'url')

### ISSUE THREAD

**Issue by Heziode** [muhamed-didovic/vsdown#3]
I get this error when I try to get the [Nuxt.js 3 Fundamentals](https://vueschool.io/courses/nuxt-js-3-fundamentals) course:

```
$ vsdown -e <REDACTED> -p <REDACTED> -d /Users/<REDACTED>/VueSchool/videos -o no -m yes https://vueschool.io/courses/nuxt-js-3-fundamentals
opts {
  email: '<REDACTED>',
  password: '<REDACTED>',
  logger: { isLogger: true },
  dir: '/Users/<REDACTED>/VueSchool/videos',
  concurrency: 10,
  overwrite: 'no',
  markdown: 'yes'
} { url: 'https://vueschool.io/courses/nuxt-js-3-fundamentals' }
✔ Login...  completed.
proCourses {: https://vueschool.io/courses/nuxt-js-3-fundamentals
  event: 'Page Viewed',
  properties: {
    page_name: 'Course',
    course: 'Nuxt.js 3 Fundamentals',
    course_id: 50
  }
}
----------------------------------------------------------------e-useasyncdata-with-options
found files: 27 in folder: /Users/<REDACTED>/VueSchool/videos/50-Nuxt.js 3 Fundamentals/screenshot
Creating PDF file from 26 images found in folder: /Users/<REDACTED>/VueSchool/videos/50-Nuxt.js 3 Fundamentals/screenshot...
PDF created at: /Users/<REDACTED>/VueSchool/videos/50-Nuxt.js 3 Fundamentals/screenshot - /Users/<REDACTED>/VueSchool/videos/50-Nuxt.js 3 Fundamentals/screenshot/Nuxt.js 3 Fundamentals.pdf Configure useAsyncData with Options.md
✓ Extraction is done for 25 videos from courses
✓ Markdown is done...
ℹ single-course - Starting writing to a file ...
ℹ Starting download with concurrency: 10 ...
ℹ single-course - Ended writing to a file ...
Noooooooooooooooooooooooooooooooooooooooooooooooo
error with findVideoUrl: https://player.vimeo.com/video/754465752?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963 -->err: TypeError: Cannot read properties of undefined (reading 'url')
    at Crawler.findVideoUrl (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:484:34)
    at /Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:430:29
    at async retry (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/helpers/retry.js:13:21)
    at async Crawler._vimeoRequest (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:414:23)
    at async Promise.all.Promise.map.concurrency.concurrency (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:558:37)
.... retrying left (6)
retrying err ReferenceError: configParsed is not defined
    at Crawler.findVideoUrl (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:487:49)
    at /Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:430:29
    at async retry (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/helpers/retry.js:13:21)
    at async Crawler._vimeoRequest (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:414:23)
    at async Promise.all.Promise.map.concurrency.concurrency (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:558:37)
Noooooooooooooooooooooooooooooooooooooooooooooooo
error with findVideoUrl: https://player.vimeo.com/video/754465685?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963 -->err: TypeError: Cannot read properties of undefined (reading 'url')
    at Crawler.findVideoUrl (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:484:34)
    at /Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:430:29
    at async retry (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/helpers/retry.js:13:21)
    at async Crawler._vimeoRequest (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:414:23)
    at async Promise.all.Promise.map.concurrency.concurrency (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:558:37)
.... retrying left (6)
retrying err ReferenceError: configParsed is not defined
    at Crawler.findVideoUrl (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:487:49)
    at /Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:430:29
    at async retry (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/helpers/retry.js:13:21)
    at async Crawler._vimeoRequest (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:414:23)
    at async Promise.all.Promise.map.concurrency.concurrency (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:558:37)
Noooooooooooooooooooooooooooooooooooooooooooooooo
error with findVideoUrl: https://player.vimeo.com/video/754465742?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963 -->err: TypeError: Cannot read properties of undefined (reading 'url')
    at Crawler.findVideoUrl (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:484:34)
    at /Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:430:29
    at async retry (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/helpers/retry.js:13:21)
    at async Crawler._vimeoRequest (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:414:23)
    at async Promise.all.Promise.map.concurrency.concurrency (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:558:37)
.... retrying left (6)
retrying err ReferenceError: configParsed is not defined
    at Crawler.findVideoUrl (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:487:49)
    at /Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:430:29
    at async retry (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/helpers/retry.js:13:21)
    at async Crawler._vimeoRequest (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:414:23)
    at async Promise.all.Promise.map.concurrency.concurrency (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:558:37)
Noooooooooooooooooooooooooooooooooooooooooooooooo
error with findVideoUrl: https://player.vimeo.com/video/754465672?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963 -->err: TypeError: Cannot read properties of undefined (reading 'url')
    at Crawler.findVideoUrl (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:484:34)
    at /Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:430:29
    at async retry (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/helpers/retry.js:13:21)
    at async Crawler._vimeoRequest (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:414:23)
    at async Promise.all.Promise.map.concurrency.concurrency (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:558:37)
.... retrying left (6)
retrying err ReferenceError: configParsed is not defined
    at Crawler.findVideoUrl (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:487:49)
    at /Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:430:29
    at async retry (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/helpers/retry.js:13:21)
    at async Crawler._vimeoRequest (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:414:23)
    at async Promise.all.Promise.map.concurrency.concurrency (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:558:37)
Noooooooooooooooooooooooooooooooooooooooooooooooo
error with findVideoUrl: https://player.vimeo.com/video/754888033?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963 -->err: TypeError: Cannot read properties of undefined (reading 'url')
    at Crawler.findVideoUrl (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:484:34)
    at /Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:430:29
    at async retry (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/helpers/retry.js:13:21)
    at async Crawler._vimeoRequest (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:414:23)
    at async Promise.all.Promise.map.concurrency.concurrency (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:558:37)
.... retrying left (6)
retrying err ReferenceError: configParsed is not defined
    at Crawler.findVideoUrl (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:487:49)
    at /Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:430:29
    at async retry (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/helpers/retry.js:13:21)
    at async Crawler._vimeoRequest (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:414:23)
    at async Promise.all.Promise.map.concurrency.concurrency (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:558:37)
Noooooooooooooooooooooooooooooooooooooooooooooooo
error with findVideoUrl: https://player.vimeo.com/video/754465537?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963 -->err: TypeError: Cannot read properties of undefined (reading 'url')
    at Crawler.findVideoUrl (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:484:34)
    at /Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:430:29
    at async retry (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/helpers/retry.js:13:21)
    at async Crawler._vimeoRequest (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:414:23)
    at async Promise.all.Promise.map.concurrency.concurrency (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:558:37)
.... retrying left (6)
retrying err ReferenceError: configParsed is not defined
    at Crawler.findVideoUrl (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:487:49)
    at /Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:430:29
    at async retry (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/helpers/retry.js:13:21)
    at async Crawler._vimeoRequest (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:414:23)
    at async Promise.all.Promise.map.concurrency.concurrency (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:558:37)
Noooooooooooooooooooooooooooooooooooooooooooooooo
error with findVideoUrl: https://player.vimeo.com/video/754465657?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963 -->err: TypeError: Cannot read properties of undefined (reading 'url')
    at Crawler.findVideoUrl (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:484:34)
    at /Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:430:29
    at async retry (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/helpers/retry.js:13:21)
    at async Crawler._vimeoRequest (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:414:23)
    at async Promise.all.Promise.map.concurrency.concurrency (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:558:37)
.... retrying left (6)
retrying err ReferenceError: configParsed is not defined
    at Crawler.findVideoUrl (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:487:49)
    at /Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:430:29
    at async retry (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/helpers/retry.js:13:21)
    at async Crawler._vimeoRequest (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:414:23)
    at async Promise.all.Promise.map.concurrency.concurrency (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:558:37)
Noooooooooooooooooooooooooooooooooooooooooooooooo
error with findVideoUrl: https://player.vimeo.com/video/754465699?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963 -->err: TypeError: Cannot read properties of undefined (reading 'url')
    at Crawler.findVideoUrl (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:484:34)
    at /Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:430:29
    at async retry (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/helpers/retry.js:13:21)
    at async Crawler._vimeoRequest (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:414:23)
    at async Promise.all.Promise.map.concurrency.concurrency (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:558:37)
.... retrying left (6)
retrying err ReferenceError: configParsed is not defined
    at Crawler.findVideoUrl (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:487:49)
    at /Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:430:29
    at async retry (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/helpers/retry.js:13:21)
    at async Crawler._vimeoRequest (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:414:23)
    at async Promise.all.Promise.map.concurrency.concurrency (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:558:37)
Noooooooooooooooooooooooooooooooooooooooooooooooo
error with findVideoUrl: https://player.vimeo.com/video/754888056?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963 -->err: TypeError: Cannot read properties of undefined (reading 'url')
    at Crawler.findVideoUrl (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:484:34)
    at /Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:430:29
    at async retry (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/helpers/retry.js:13:21)
    at async Crawler._vimeoRequest (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:414:23)
    at async Promise.all.Promise.map.concurrency.concurrency (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:558:37)
.... retrying left (6)
retrying err ReferenceError: configParsed is not defined
    at Crawler.findVideoUrl (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:487:49)
    at /Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:430:29
    at async retry (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/helpers/retry.js:13:21)
    at async Crawler._vimeoRequest (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:414:23)
    at async Promise.all.Promise.map.concurrency.concurrency (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:558:37)
Noooooooooooooooooooooooooooooooooooooooooooooooo
error with findVideoUrl: https://player.vimeo.com/video/754465713?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963 -->err: TypeError: Cannot read properties of undefined (reading 'url')
    at Crawler.findVideoUrl (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:484:34)
    at /Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:430:29
    at async retry (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/helpers/retry.js:13:21)
    at async Crawler._vimeoRequest (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:414:23)
    at async Promise.all.Promise.map.concurrency.concurrency (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:558:37)
.... retrying left (6)
retrying err ReferenceError: configParsed is not defined
    at Crawler.findVideoUrl (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:487:49)
    at /Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:430:29
    at async retry (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/helpers/retry.js:13:21)
    at async Crawler._vimeoRequest (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:414:23)
    at async Promise.all.Promise.map.concurrency.concurrency (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:558:37)
ERROR with vimeoUrl: https://player.vimeo.com/video/754465752?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963 vvvv: undefined
ERR:: TypeError: this.retry is not a function
    at retry (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/helpers/retry.js:20:25)
    at async Crawler._vimeoRequest (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:414:23)
    at async Promise.all.Promise.map.concurrency.concurrency (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:558:37)
ERROR with vimeoUrl: https://player.vimeo.com/video/754465685?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963 vvvv: undefined
ERR:: TypeError: this.retry is not a function
    at retry (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/helpers/retry.js:20:25)
    at async Crawler._vimeoRequest (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:414:23)
    at async Promise.all.Promise.map.concurrency.concurrency (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:558:37)
MAIN errorr: TypeError: this.retry is not a function
    at retry (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/helpers/retry.js:20:25)
    at async Crawler._vimeoRequest (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:414:23)
    at async Promise.all.Promise.map.concurrency.concurrency (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:558:37)
From previous event:
    at processImmediate (node:internal/timers:466:21)
From previous event:
    at /Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:546:31
    at Crawler.d (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/Crawler.js:581:15)
    at exports.one (/Users/<REDACTED>/.nvm/versions/node/v16.15.0/lib/node_modules/vsdown/lib/index.js:44:19)
```

I have not had this problem with other courses.

**Comment by muhamed-didovic** [comment]
Hi @Heziode, there is new version: vsdown@0.5.6, please update it and let me know

**Comment by Heziode** [comment]
Download works now.

However, this create some display error (no throwing error) like:

```
24. Video already downloaded: 25. Course Conclusion.mp4 - 14.33 MB/NaN undefined
```

There is an other trouble: it only downloads subtitles in Spanish and in a separate `.vtt` file.

Here is the rest of the log from the first post with 0.5.6:

```
✓ Extraction is done for 25 videos from courses
✓ Markdown is done...
ℹ single-course - Starting writing to a file ...
ℹ Starting download with concurrency: 10 ...
ℹ single-course - Ended writing to a file ...
No progressive url found: https://player.vimeo.com/video/754465537?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963
No progressive url found: https://player.vimeo.com/video/754465672?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963
2. Video already downloaded: 3. File Based Routing in Nuxt.js.mp4 - 16.51 MB/NaN undefined
No progressive url found: https://player.vimeo.com/video/754465657?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963
1. Video already downloaded: 2. Create a Nuxt App from Scratch.mp4 - 18.15 MB/NaN undefined
No progressive url found: https://player.vimeo.com/video/754465713?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963
5. Video already downloaded: 6. Fetch Data with $fetch.mp4 - 34.39 MB/NaN undefined
No progressive url found: https://player.vimeo.com/video/754465685?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963
3. Video already downloaded: 4. NuxtLink for Navigation.mp4 - 14.77 MB/NaN undefined
No progressive url found: https://player.vimeo.com/video/762764732?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963
24. Video already downloaded: 25. Course Conclusion.mp4 - 14.33 MB/NaN undefined
No progressive url found: https://player.vimeo.com/video/762685430?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963
No progressive url found: https://player.vimeo.com/video/762684877?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963
No progressive url found: https://player.vimeo.com/video/762684636?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963
21. Video already downloaded: 22. Overview of Nuxt Deployment Options.mp4 - 13.53 MB/NaN undefined
No progressive url found: https://player.vimeo.com/video/754465699?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963
4. Video already downloaded: 5. Dynamic Route Params in Nuxt.js.mp4 - 14.53 MB/NaN undefinedd
No progressive url found: https://player.vimeo.com/video/754465742?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963
6. Video already downloaded: 7. Provide a Single Root Element for Page Components.mp4 - 8.22 MB/NaN undefined
No progressive url found: https://player.vimeo.com/video/754888056?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963
9. Video already downloaded: 10. De-dupe Async Data with a Key.mp4 - 15.92 MB/NaN undefined
No progressive url found: https://player.vimeo.com/video/754465752?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963
7. Video already downloaded: 8. Create Components that Auto Import.mp4 - 10.94 MB/NaN undefined
No progressive url found: https://player.vimeo.com/video/754888033?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963
8. Video already downloaded: 9. Fetch data with useAsyncData.mp4 - 15.28 MB/NaN undefined
No progressive url found: https://player.vimeo.com/video/762683996?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963
No progressive url found: https://player.vimeo.com/video/762721439?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963
No progressive url found: https://player.vimeo.com/video/761468863?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963
No progressive url found: https://player.vimeo.com/video/761468787?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963ned
No progressive url found: https://player.vimeo.com/video/761471577?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963
No progressive url found: https://player.vimeo.com/video/761468905?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963ned
No progressive url found: https://player.vimeo.com/video/758785411?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963ned
0. End download yt-dlp: /Users/<REDACTED>/VueSchool/videos/50-Nuxt.js 3 Fundamentals/1. What is Nuxt.mp4 Found:0 Bytes/NaN undefined - Size:50.13 MB Bytes/NaN undefined
No progressive url found: https://player.vimeo.com/video/755292436?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963
22. End download yt-dlp: /Users/<REDACTED>/VueSchool/videos/50-Nuxt.js 3 Fundamentals/23. Deploy a Nuxt Site to Netlify.mp4 Found:0 Bytes/NaN undefined - Size:25.8 MB
17. End download yt-dlp: /Users/<REDACTED>/VueSchool/videos/50-Nuxt.js 3 Fundamentals/18. Nuxt Server API Routes.mp4 Found:0 Bytes/NaN undefined - Size:16.68 MB
No progressive url found: https://player.vimeo.com/video/754911096?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963
No progressive url found: https://player.vimeo.com/video/754910994?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963
18. End download yt-dlp: /Users/<REDACTED>/VueSchool/videos/50-Nuxt.js 3 Fundamentals/19. Handle Different Nuxt API Request Methods.mp4 Found:0 Bytes/NaN undefined - Size:24.38 MB
No progressive url found: https://player.vimeo.com/video/754888100?h=441c7816f6&title=0&byline=0&portrait=0&app_id=122963
16. End download yt-dlp: /Users/<REDACTED>/VueSchool/videos/50-Nuxt.js 3 Fundamentals/17. Abort Navigation or Redirect In Nuxt Middleware.mp4 Found:0 Bytes/NaN undefined - Size:21.39 MB
11. End download yt-dlp: /Users/<REDACTED>/VueSchool/videos/50-Nuxt.js 3 Fundamentals/12. Call useFetch for a $fetch + useAsyncData Shorthand.mp4 Found:0 Bytes/NaN undefined - Size:7.78 MB
14. End download yt-dlp: /Users/<REDACTED>/VueSchool/videos/50-Nuxt.js 3 Fundamentals/15. Create Flexible Custom Layouts.mp4 Found:0 Bytes/NaN undefined - Size:16.76 MB
15. End download yt-dlp: /Users/<REDACTED>/VueSchool/videos/50-Nuxt.js 3 Fundamentals/16. Define Nuxt Route Middleware.mp4 Found:0 Bytes/NaN undefined - Size:21.37 MB
23. End download yt-dlp: /Users/<REDACTED>/VueSchool/videos/50-Nuxt.js 3 Fundamentals/24. Hybrid Rendering with Nuxt.mp4 Found:0 Bytes/NaN undefined - Size:50.68 MBNuxt.mp4 Found:0 Bytes/NaN undefined
19. End download yt-dlp: /Users/<REDACTED>/VueSchool/videos/50-Nuxt.js 3 Fundamentals/20. Global State Management with useState.mp4 Found:0 Bytes/NaN undefined - Size:35.82 MBnt with Pinia.mp4 Found:0 Bytes/NaN undefined
20. End download yt-dlp: /Users/<REDACTED>/VueSchool/videos/50-Nuxt.js 3 Fundamentals/21. Global State Management with Pinia.mp4 Found:0 Bytes/NaN undefined - Size:35.06 MBement with Pinia.mp4 Found:0 Bytes/NaN undefined
10. End download yt-dlp: /Users/<REDACTED>/VueSchool/videos/50-Nuxt.js 3 Fundamentals/11. Configure useAsyncData with Options.mp4 Found:0 Bytes/NaN undefined - Size:19.87 MB
13. End download yt-dlp: /Users/<REDACTED>/VueSchool/videos/50-Nuxt.js 3 Fundamentals/14. Call the useHead Composable for Good SEO.mp4 Found:0 Bytes/NaN undefined - Size:27.87 MBsable for Good SEO.mp4 Found:0 Bytes/NaN undefined
12. End download yt-dlp: /Users/<REDACTED>/VueSchool/videos/50-Nuxt.js 3 Fundamentals/13. Handle useFetch Errors.mp4 Found:0 Bytes/NaN undefined - Size:24.06 MB
✔ Downloaded all videos for 'single-course' api! (total: 25)
```

**Comment by muhamed-didovic** [comment]
Hi @Heziode, 

There is a new version, please update.

Regarding 'error output', that is when the download size can't be calculated, in the end, it is just a log message.
For subtitles, I download with yt-dlp what can be downloaded and that is it.

**Comment by Heziode** [comment]
Okey,

This works.

> Regarding 'error output', that is when the download size can't be calculated, in the end, it is just a log message.

Still present and yes, it is not very problematic.

> For subtitles, I download with yt-dlp what can be downloaded and that is it.

Strange. In you code, you have two calls to `yt-dlp`, which one is realy used to download video? Since one attempt to download the video with all subtitles (includes auto), and the other seems is more general

**Comment by muhamed-didovic** [comment]
hey @Heziode, yes there are  two versions one is youtube-dl which doesn't work any more with vimeo so I added  yt-dlp which works with vimeo download
